### ISSUE TITLE
No handler for Heartbeat

### ISSUE THREAD

**Issue by MGGEL** [mobilityhouse/ocpp#111]
I am trying to establish a connection to a Keba wallbox. The wallbox constantly sends a heartbeat. Which ends with the following error:

```python
INFO:ocpp:Wallbox001_Test: receive message [2,"a53bc09e-90fc-4dd6-967b-231703da55a9","Heartbeat",{}]
ERROR:websockets.server:Error in connection handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ocpp/charge_point.py", line 161, in _handle_call
    handlers = self.route_map[msg.action]
KeyError: 'Heartbeat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
  File "test.py", line 40, in on_connect
    await cp.start()
  File "/usr/local/lib/python3.8/dist-packages/ocpp/charge_point.py", line 125, in start
    await self.route_message(message)
  File "/usr/local/lib/python3.8/dist-packages/ocpp/charge_point.py", line 143, in route_message
    await self._handle_call(msg)
  File "/usr/local/lib/python3.8/dist-packages/ocpp/charge_point.py", line 163, in _handle_call
    raise NotImplementedError(f"No handler for '{msg.action}' "
ocpp.exceptions.NotImplementedError: No handler for 'Heartbeat' registered.
```

I can't find any possibility to disable the heartbeat. 

How can I handle this?

**Comment by OrangeTux** [comment]
> I can't find any possibility to disable the heartbeat. 

You can't disable the heartbeat using OCPP. You could configure a very large heartbeat interval. That is done using the response on a BootNotification.

Alternatively you can implement a handler for the Hearbeat message. Is trivial to do.


``` python

import ocpp

class CP(ocpp.v16.ChargePoint):
    ...
    @route.on("Heartbeat")
    def on_heartbeat(self):
        return ocpp.v16.call_result.HeartbeatPayload(
            current_time=datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S') + "Z"
         )
```
