### ISSUE TITLE
ocpp.exceptions.NotImplementedError: NotImplementedError: No handler for 'StartTransaction' registered

### ISSUE THREAD

**Issue by dinko-pehar** [mobilityhouse/ocpp#232]
Greeting to you all.

I'm working with your library, using many other frameworks and libraries as foundation (_sanic and websockets_).

While everything works great, I stumbled upon this kind of error (_debug logs enabled_):

``` python
cp_2: receive message [2,"iLKqs1F83pjyAyhIwKA8EbVe3XMIHSVWo17s","StartTransaction",{"connectorId":2,"idTag":"B4A63CDF","timestamp":"2021-07-25T14:53:14Z","meterStart":0,"reservationId":0}]
[2021-07-25 14:53:14 +0200] [20823] [ERROR] Exception occurred while handling uri: 'ws://127.0.0.1:8888/ws/cp_2'
Traceback (most recent call last):
  File "/home/dinko/Projects/ocpp-backend/.direnv/python-3.9.6/lib/python3.9/site-packages/ocpp/charge_point.py", line 162, in _handle_call
    handlers = self.route_map[msg.action]
KeyError: 'StartTransaction'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dinko/Projects/ocpp-backend/.direnv/python-3.9.6/lib/python3.9/site-packages/sanic/app.py", line 821, in _websocket_handler
    await fut
  File "/home/dinko/Projects/ocpp-backend/app/ws/feed.py", line 103, in feed
    await cp.start()
  File "/home/dinko/Projects/ocpp-backend/.direnv/python-3.9.6/lib/python3.9/site-packages/ocpp/charge_point.py", line 126, in start
    await self.route_message(message)
  File "/home/dinko/Projects/ocpp-backend/.direnv/python-3.9.6/lib/python3.9/site-packages/ocpp/charge_point.py", line 144, in route_message
    await self._handle_call(msg)
  File "/home/dinko/Projects/ocpp-backend/.direnv/python-3.9.6/lib/python3.9/site-packages/ocpp/charge_point.py", line 164, in _handle_call
    raise NotImplementedError(f"No handler for '{msg.action}' "
ocpp.exceptions.NotImplementedError: NotImplementedError: No handler for 'StartTransaction' registered., {}

```

I'm not sure why I'm getting this error, because I have registered a handlers for each action in similar way:

```python
class ChargePointWSHandler(ChargePoint):
    """Handler for each Charging Point.
    
    Handling is enabled by `@on` decorator which contains
    each action with it's proper response.
    """
    
    @on(Action.BootNotification)
    async def on_boot_notification(self, **kwargs):

        # Handling etc.

        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().isoformat(),
            interval=10,
            status='Accepted'
        )
    
    @on(Action.Heartbeat)
    async def on_heartbeat(self, **kwargs):

        # Handling

        return call_result.HeartbeatPayload(
            current_time=datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S') + "Z"
        )
    
    @on(Action.StartTransaction)
    async def on_start_transaction_payload(self, **kwargs):

        return call_result.StartTransactionPayload(
            transaction_id=random.randint(1, 10000),
            id_tag_info={"status":"expired"}
        )
```

I have tried changing from `@on(Action.StartTransaction)` to `@on("StartTransaction")` because that also works with other, for example _BootNotification_ and _Heartbeat_ but for StartTransaction and StopTransaction, nothing currently works.

All help is appreciated.

**Comment by OrangeTux** [comment]
Hello @dinko-pehar ,

I'm unfortunately unable to reproduce the issue. I used the following code:

``` python
import asyncio
import logging
import random
from datetime import datetime
import websockets
from ocpp.routing import on
from ocpp.v16 import ChargePoint, call_result
from ocpp.v16.enums import Action


class ChargePointWSHandler(ChargePoint):
    """Handler for each Charging Point.

    Handling is enabled by `@on` decorator which contains
    each action with it's proper response.
    """

    @on(Action.BootNotification)
    async def on_boot_notification(self, **kwargs):

        # Handling etc.

        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().isoformat(), interval=10, status="Accepted"
        )

    @on(Action.Heartbeat)
    async def on_heartbeat(self, **kwargs):

        # Handling

        return call_result.HeartbeatPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S") + "Z"
        )

    @on(Action.StartTransaction)
    async def on_start_transaction_payload(self, **kwargs):

        return call_result.StartTransactionPayload(
            transaction_id=random.randint(1, 10000), id_tag_info={"status": "Expired"}
        )


async def on_connect(websocket, path):
    """For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
    try:
        requested_protocols = websocket.request_headers["Sec-WebSocket-Protocol"]
    except KeyError:
        logging.error("Client hasn't requested any Subprotocol. Closing Connection")
        return await websocket.close()
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning(
            "Protocols Mismatched | Expected Subprotocols: %s,"
            " but client supports  %s | Closing connection",
            websocket.available_subprotocols,
            requested_protocols,
        )
        return await websocket.close()

    charge_point_id = path.strip("/")
    cp = ChargePointWSHandler(charge_point_id, websocket)

    await cp.start()


async def main():
    server = await websockets.serve(
        on_connect, "0.0.0.0", 9000, subprotocols=["ocpp1.6"]
    )

    logging.info("Server Started listening to new connections...")
    await server.wait_closed()


if __name__ == "__main__":
    try:
        # asyncio.run() is used when running this example with Python 3.7 and
        # higher.
        asyncio.run(main())
    except AttributeError:
        # For Python 3.6 a bit more code is required to run the main() task on
        # an event loop.
        loop = asyncio.get_event_loop()
        loop.run_until_complete(main())
        loop.close()
```

``` python
import asyncio
import logging
from datetime import datetime

try:
    import websockets
except ModuleNotFoundError:
    print("This example relies on the 'websockets' package.")
    print("Please install it by running: ")
    print()
    print(" $ pip install websockets")
    import sys

    sys.exit(1)


from ocpp.v16 import call
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import RegistrationStatus

logging.basicConfig(level=logging.INFO)


class ChargePoint(cp):
    async def send_boot_notification(self):
        request = call.BootNotificationPayload(
            charge_point_model="Optimus", charge_point_vendor="The Mobility House"
        )

        response = await self.call(request)

        if response.status == RegistrationStatus.accepted:
            print("Connected to central system.")

    async def start_transaction(self):
        request = call.StartTransactionPayload(
            id_tag="1",
            connector_id=1,
            meter_start=2,
            timestamp=datetime.utcnow().isoformat(),
        )

        _response = await self.call(request)


async def main():
    async with websockets.connect(
        "ws://localhost:9000/CP_1", subprotocols=["ocpp1.6"]
    ) as ws:

        cp = ChargePoint("CP_1", ws)

        await asyncio.gather(
            cp.start(), cp.send_boot_notification(), cp.start_transaction()
        )


if __name__ == "__main__":
    try:
        # asyncio.run() is used when running this example with Python 3.7 and
        # higher.
        asyncio.run(main())
    except AttributeError:
        # For Python 3.6 a bit more code is required to run the main() task on
        # an event loop.
        loop = asyncio.get_event_loop()
        loop.run_until_complete(main())
        loop.close()
```

**Comment by dinko-pehar** [comment]
I didn't provide whole example, thinking that something was wrong with `StartTransaction`. But actually I registered same method with different decorators due to copy paste:

```
...
@on(Action.StartTransaction)
    async def on_start_transaction_payload(self, **kwargs):

        return call_result.StartTransactionPayload(
            transaction_id=random.randint(1, 10000),
            id_tag_info={"status":"expired"}
        )
@on(Action.StopTransaction)
    async def on_start_transaction_payload(self, **kwargs):

        return call_result.StopTransactionPayload(
            transaction_id=random.randint(1, 10000),
            id_tag_info={"status":"expired"}
        )
```

I didn't understand at first, than I saw that I redefined same method twice :disappointed: .

---

Thank you for your time and complete working example :rocket: .

**Comment by OrangeTux** [comment]
Great that the issue is solved!
