### ISSUE TITLE
Disconnect will show error in the console 

### ISSUE THREAD

**Issue by saeedCodium** [mobilityhouse/ocpp#234]
When I want to Disconnect I will receive this error in the console how can I handle it when the Disconnect command came from the frontend? 

``` python
ERROR:websockets.server:Error in connection handler
Traceback (most recent call last):
  File "/Users/saeedrahmatolahi/Library/Python/3.8/lib/python/site-packages/websockets/legacy/server.py", line 293, in handler
    await self.ws_handler(self, path)
  File ".../central_system.py", line 69, in on_connect
    await charge_point.start()
  File ".../charge_point.py", line 123, in start
    message = await self._connection.recv()
  File ".../protocol.py", line 421, in recv
    await self.ensure_open()
  File ".../protocol.py", line 735, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 3001 (registered), reason = close connection
```
here is my codes 
``` python
import asyncio
import logging
from datetime import datetime

from ocpp.v16.call import AuthorizePayload

try:
    import websockets
except ModuleNotFoundError:
    import sys
    print('error')
    sys.exit(1)

from ocpp.routing import on
from ocpp.v201 import ChargePoint as cp
from ocpp.v201 import call_result

logging.basicConfig(level=logging.INFO)


class ChargePoint(cp):
    @on('BootNotification', skip_schema_validation=True)
    def on_boot_notification(self, charging_station, reason, **kwargs):
        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().isoformat(),
            interval=10,
            status='Accepted'
        )

    @on('Heartbeat')
    def on_heartbeat(self):
        print('Got a Heartbeat!')
        return call_result.HeartbeatPayload(
            current_time=datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S') + "Z"
        )

    @on('Authorize', skip_schema_validation=True)
    def on_authorize(self):
        return call_result.AuthorizePayload(
            id_token_info={"id_tag": 23},
        )


async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
    try:
        requested_protocols = websocket.request_headers['Sec-WebSocket-Protocol']
    except KeyError:
        logging.info("Client hasn't requested any Sub protocol. "
                     "Closing Connection")
        logging.error("Client hasn't requested any Sub protocol. Closing Connection")
        return await websocket.close()
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning('Protocols Mismatched | Expected Subprotocols: %s,'
                        ' but client supports %s | Closing connection',
                        websocket.available_subprotocols,
                        requested_protocols)
        return await websocket.close()

    charge_point_id = path.strip('/')
    charge_point = ChargePoint(charge_point_id, websocket)
    await charge_point.start()


async def main():
    #  deep code ignore BindToAllNetworkInterfaces: <Example Purposes>
    server = await websockets.serve(
        on_connect,
        '0.0.0.0',
        9000,
        subprotocols=['ocpp1.6']
    )

    logging.info("Server Started listening to new connections...")
    await server.wait_closed()
    # server.close()

if __name__ == '__main__':
    try:
        # asyncio.run() is used when running this example with Python 3.7 and
        # higher.
        asyncio.run(main())
    except AttributeError:
        # For Python 3.6 a bit more code is required to run the main() task on
        # an event loop.
        loop = asyncio.get_event_loop()
        loop.run_until_complete(main())
        loop.close()

```

**Comment by OrangeTux** [comment]
Hello @saeedCodium ,

The exception bubbles up to your code at:

``` python
  File ".../central_system.py", line 69, in on_connect
    await charge_point.start()
```

So wrapping that in a `try/except` allows you to catch the exception:


``` python
async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """ 
    ...
    charge_point_id = path.strip('/')
    charge_point = ChargePoint(charge_point_id, websocket)
    try:
        await charge_point.start()
    except websockets.exceptions.ConnectionClosedError:
        // Do something
        ...
 ```

**Comment by SaeedRahmatolahi** [comment]
thanks it solved that problem and I am getting this error after that in the console 
```/.../central_system.py:87: RuntimeWarning: coroutine 'WebSocketCommonProtocol.close' was never awaited
  websocket.close()```
  because in `except` part I used `websocket.close()` is that correct or not?

**Comment by OrangeTux** [comment]
You seem to be referring to a new error when you mention 'this error'. But I don't understand what error you mean. Can you elaborate?

**Comment by SaeedRahmatolahi** [comment]
I wrote the error

**Comment by OrangeTux** [comment]
`websocket.close()` is a coroutine, so it need to be `await`ed. So

``` python
await websocket.close()
```

**Comment by SaeedRahmatolahi** [comment]
> `websocket.close()` is a coroutine, so it need to be `await`ed. So
> 
> ```python
> await websocket.close()
> ```

thanks
