### ISSUE TITLE
Tests started to fail in CircleCI

### ISSUE THREAD

**Issue by laysauchoa** [mobilityhouse/ocpp#252]
Locally, I have run:
```
make deps && make test
```
But this step is failing in the circleci [here](https://app.circleci.com/pipelines/github/mobilityhouse/ocpp/427/workflows/c4d6a24e-cc7a-4d9c-b2ee-1278b03b11b2/jobs/1263) and basically just a text on [README](https://github.com/mobilityhouse/ocpp/commit/a454235df30f9dce405a49219f4f3e7cd239a1de) was changed as a possible test.

**Comment by OrangeTux** [comment]
Interesting catch. I [reran a build](https://app.circleci.com/pipelines/github/mobilityhouse/ocpp?branch=master) that previously worked and this build starts to fail now as well. It seems that the build is not reproducible.

**Comment by OrangeTux** [comment]
It seems that a recent version of `poetry` contains a bug. See https://github.com/python-poetry/poetry/issues/4523  As the build doesn't pins the version of `poetry` the latest version is installed. Thanks @Roger for figuring this out.

**Comment by Roger** [comment]
After digging a bit more, looks like our issue is that our lockfile is in an old format that doesn't contain the algo in the hashes and since we didn't add any dependency to the project for so long, it didn't update to the latest format and at some point became backwards incompatible https://github.com/python-poetry/poetry/issues/4523#issuecomment-925075103

Running `poetry lock --no-update` should fix the issue

**Comment by laysauchoa** [comment]
@Roger this is what I get when I run poetry `lock --no-update`. 

```
✦ ➜ poetry lock --no-update

[NoSuchOptionException]
The "--no-update" option does not exist.

Traceback (most recent call last):
  File "/home/tmhdev/.local/lib/python3.6/site-packages/clikit/console_application.py", line 124, in run
    self, args, input_stream, output_stream, error_stream
  File "/home/tmhdev/.local/lib/python3.6/site-packages/poetry/console/config/application_config.py", line 165, in create_io
    resolved_command = application.resolve_command(args)
  File "/home/tmhdev/.local/lib/python3.6/site-packages/clikit/console_application.py", line 110, in resolve_command
    return self._config.command_resolver.resolve(args, self)
  File "/home/tmhdev/.local/lib/python3.6/site-packages/clikit/resolver/default_resolver.py", line 34, in resolve
    return self.create_resolved_command(result)
  File "/home/tmhdev/.local/lib/python3.6/site-packages/clikit/resolver/default_resolver.py", line 166, in create_resolved_command
    if not result.is_parsable():
  File "/home/tmhdev/.local/lib/python3.6/site-packages/clikit/resolver/resolve_result.py", line 43, in is_parsable
    self._parse()
  File "/home/tmhdev/.local/lib/python3.6/site-packages/clikit/resolver/resolve_result.py", line 49, in _parse
    self._parsed_args = self._command.parse(self._raw_args)
  File "/home/tmhdev/.local/lib/python3.6/site-packages/clikit/api/command/command.py", line 113, in parse
    return self._config.args_parser.parse(args, self._args_format, lenient)
  File "/home/tmhdev/.local/lib/python3.6/site-packages/clikit/args/default_args_parser.py", line 53, in parse
    self._parse(args, _fmt, lenient)
  File "/home/tmhdev/.local/lib/python3.6/site-packages/clikit/args/default_args_parser.py", line 101, in _parse
    self._parse_long_option(token, tokens, fmt, lenient)
  File "/home/tmhdev/.local/lib/python3.6/site-packages/clikit/args/default_args_parser.py", line 247, in _parse_long_option
    self._add_long_option(name, None, tokens, fmt, lenient)
  File "/home/tmhdev/.local/lib/python3.6/site-packages/clikit/args/default_args_parser.py", line 300, in _add_long_option
    raise NoSuchOptionException(name)

```

**Comment by OrangeTux** [comment]
What version of `poetry` are you using? This flag has been added in version 1.1.1, see https://python-poetry.org/history/#111---2020-10-05

**Comment by laysauchoa** [comment]
The version of poetry that I am using is:
Poetry version 1.1.10

Locally, the tests are passing, but in circle ci is failing.
