### ISSUE TITLE
Action.Heartbeat has no payload response and causes handler to break

### ISSUE THREAD

**Issue by esiebert** [mobilityhouse/ocpp#28]
When class handles `Action.Heartbeat`, it returns no payload, causing `charge_point.py` to break:
```
ChargePoint Vendor is: Virtual Charge Point
ChargePoint Model is: Generic
Got heartbeat
Error in connection handler
Traceback (most recent call last):
  File "/home/esiebert/anaconda3/lib/python3.7/site-packages/websockets/server.py", line 195, in handler
    await self.ws_handler(self, path)
  File "./central.py", line 40, in on_connect
    await cp.start()
  File "/home/esiebert/anaconda3/lib/python3.7/site-packages/ocpp/v16/charge_point.py", line 126, in start
    await self.route_message(message)
  File "/home/esiebert/anaconda3/lib/python3.7/site-packages/ocpp/v16/charge_point.py", line 144, in route_message
    await self._handle_call(msg)
  File "/home/esiebert/anaconda3/lib/python3.7/site-packages/ocpp/v16/charge_point.py", line 189, in _handle_call
    temp_response_payload = asdict(response)
  File "/home/esiebert/anaconda3/lib/python3.7/dataclasses.py", line 1043, in asdict
    raise TypeError("asdict() should be called on dataclass instances")
TypeError: asdict() should be called on dataclass instances
```
The class:
```python
class Central(ChargePoint):
    @on(Action.Heartbeat)
    def on_heartbeat(self, **kwargs):
        print("Got heartbeat")

```

**Comment by pagetable** [comment]
Heartbeat.conf has a required field 'currentTime'. Hence, you should return dataclass 'call_result.HeartbeatPayload' in on_heartbeat(). Then, this issue will not exist.

**Comment by andcan86** [comment]
Hi all, I am having the exact same issue as reported here, even after setting the (seemingly) correct response from the central system (using ocpp 1.6):

```
    @on(Action.Heartbeat)
    async def on_heartbeat(self, **kwargs):  # receives empty payload from CP
        print("--HeartBeat--")
        print(kwargs)
        call_result.HeartbeatPayload(
            current_time=f"{datetime.now()}"
        )
```

The stack Trace is the following (please note that ws connection and BootNotifications work, and that the HeartBeat msg from the CP is also received as expected)

←[32mINFO←[0m:     Started server process [←[36m95096←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
2021-06-28 16:28:29,536 - APP Logger - INFO - o, c, p, p, 1, ., 6
2021-06-28 16:28:29,536 - APP Logger - INFO - Protocols Matched: ['o', 'c', 'p', 'p', '1', '.', '6']
2021-06-28 16:28:29,536 - APP Logger - INFO - Validation approved
←[32mINFO←[0m:     ('127.0.0.1', 56834) - "WebSocket /ws/test/CP_1" [accepted]
2021-06-28 16:28:29,536 - APP Logger - INFO - CP_1 setting conn: <models.websocket_wrapper.WebSocketWrapper object at 0x0000027528B14F40>
--BootNotification--
{'charge_point_model': 'CP_1', 'charge_point_vendor': 'test'}
--HeartBeat--
{}
←[31mERROR←[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\cazzaniga\AppData\Roaming\Python\Python38\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 162, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "C:\Users\cazzaniga\AppData\Roaming\Python\Python38\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\cazzaniga\AppData\Roaming\Python\Python38\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\cazzaniga\AppData\Roaming\Python\Python38\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\cazzaniga\AppData\Roaming\Python\Python38\site-packages\starlette\middleware\errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\cazzaniga\AppData\Roaming\Python\Python38\site-packages\starlette\exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\cazzaniga\AppData\Roaming\Python\Python38\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\cazzaniga\AppData\Roaming\Python\Python38\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\cazzaniga\AppData\Roaming\Python\Python38\site-packages\starlette\routing.py", line 68, in app
    await func(session)
  File "C:\Users\cazzaniga\AppData\Roaming\Python\Python38\site-packages\fastapi\routing.py", line 247, in app
    await dependant.call(**values)
  File ".\main.py", line 83, in websocket_endpoint
    await cm.connect_charge_point(
  File ".\models\ws_connection_manager.py", line 102, in connect_charge_point
    await cp.start()
  File "C:\Users\cazzaniga\AppData\Roaming\Python\Python38\site-packages\ocpp\charge_point.py", line 126, in start
    await self.route_message(message)
  File "C:\Users\cazzaniga\AppData\Roaming\Python\Python38\site-packages\ocpp\charge_point.py", line 144, in route_message
    await self._handle_call(msg)
  File "C:\Users\cazzaniga\AppData\Roaming\Python\Python38\site-packages\ocpp\charge_point.py", line 195, in _handle_call
    temp_response_payload = asdict(response)
  File "c:\program files\python38\lib\dataclasses.py", line 1072, in asdict
    raise TypeError("asdict() should be called on dataclass instances")
TypeError: asdict() should be called on dataclass instances


Could you help me please understand if I am doing something wrong? I tried different string formatting for the current_timestamp but no one worked, and the error message did not mention anything about a failure in the string processing. 

Thank you very much in advance,

**Comment by tropxy** [comment]
You should do like this:
```python
@on(Action.Heartbeat)
    async def on_heartbeat(self, **kwargs):  # receives empty payload from CP
        print("--HeartBeat--")
        print(kwargs)
        return call_result.HeartbeatPayload(
                 current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
         )

```

**Comment by andcan86** [comment]
yes, you are definitivey right and I am an **! 
I forgot the return, thanks a lot
