### ISSUE TITLE
Importing certain modules leads to: ImportError: cannot import name 'Call'

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#31]
Import some modules of ocpp lead to import errors.

E.g.:

``` python
$ python -m ocpp.messages.Call
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/tmp/.env/lib/python3.6/site-packages/ocpp/messages.py", line 10, in <module>
    from ocpp.v16.enums import MessageType
  File "/tmp/.env/lib/python3.6/site-packages/ocpp/v16/__init__.py", line 1, in <module>
    from ocpp.v16.charge_point import ChargePoint  # noqa: F401
  File "/tmp/.env/lib/python3.6/site-packages/ocpp/v16/charge_point.py", line 9, in <module>
    from ocpp.messages import Call
ImportError: cannot import name 'Call'
```

**Comment by OrangeTux** [comment]
This issue has been fixed in 44742f74a88bdfc, which was part of version 0.4.0
