### ISSUE TITLE
Heartbeat Error

### ISSUE THREAD

**Issue by pamukcu09** [mobilityhouse/ocpp#405]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
```
  File "C:\Users\user\PycharmProjects\pythonProject\venv\Lib\site-packages\ocpp\charge_point.py", line 150, in route_message
    await self._handle_call(msg)
  File "C:\Users\user\PycharmProjects\pythonProject\venv\Lib\site-packages\ocpp\charge_point.py", line 174, in _handle_call
    raise NotSupportedError(
ocpp.exceptions.NotSupportedError: NotSupportedError: Request Action is recognized but not supported by the receiver, {'cause': 'No handler for Heartbeat registered.'}
INFO:ocpp:ws://192.168.7.100:9000: send [4,"1000006","NotSupported","Request Action is recognized but not supported by the receiver",{"cause":"No handler for Heartbeat registered."}]
INFO:ocpp:ws://192.168.7.100:9000: receive message [2,"1000007","Heartbeat",{}]
ERROR:ocpp:Error while handling request '<Call - unique_id=1000007, action=Heartbeat, payload={}>'
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\pythonProject\venv\Lib\site-packages\ocpp\charge_point.py", line 172, in _handle_call
    handlers = self.route_map[msg.action]
               ~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'Heartbeat'
```

**Comment by pamukcu09** [comment]
Hi. I need help on why this error occurs.Thank you

**Comment by OrangeTux** [comment]
The code received a Heartbeat message. However, the code didn't implement a handler for it. Make sure to implement the handler.

**Comment by pamukcu09** [comment]
thanks for your answer
