### ISSUE TITLE
KeyError: 'TriggerMessage'

### ISSUE THREAD

**Issue by DvlprSG** [mobilityhouse/ocpp#446]
I am trying to send some requests like BootNotification, Authorization, StatusNotification, StartTransaction, Meter Values and StopTransaction. All are working fine, I am getting the response from CSMS but i am getting some exceptions which are mentioned below:

```
ERROR:ocpp:Error while handling request '<Call - unique_id=153291687523070501:TM, action=TriggerMessage, payload={'requestedMessage': 'StatusNotification', 'connectorId': 1}>'
Traceback (most recent call last):
  File "/home/lenovo/.local/lib/python3.8/site-packages/ocpp/charge_point.py", line 174, in _handle_call
    handlers = self.route_map[msg.action]
KeyError: 'TriggerMessage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lenovo/.local/lib/python3.8/site-packages/ocpp/charge_point.py", line 153, in route_message
    await self._handle_call(msg)
  File "/home/lenovo/.local/lib/python3.8/site-packages/ocpp/charge_point.py", line 176, in _handle_call
    raise NotSupportedError(
ocpp.exceptions.NotSupportedError: NotSupportedError: Request Action is recognized but not supported by the receiver, {'cause': 'No handler for TriggerMessage registered.'}
INFO:ocpp:CP_1: send [4,"153291687523070501:TM","NotSupported","Request Action is recognized but not supported by the receiver",{"cause":"No handler for TriggerMessage registered."}]
INFO:ocpp:CP_1: receive message [2,"153291687523070501:TM","TriggerMessage",{"requestedMessage":"StatusNotification","connectorId":2}]
ERROR:ocpp:Error while handling request '<Call - unique_id=153291687523070501:TM, action=TriggerMessage, payload={'requestedMessage': 'StatusNotification', 'connectorId': 2}>'
Traceback (most recent call last):
  File "/home/lenovo/.local/lib/python3.8/site-packages/ocpp/charge_point.py", line 174, in _handle_call
    handlers = self.route_map[msg.action]
KeyError: 'TriggerMessage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lenovo/.local/lib/python3.8/site-packages/ocpp/charge_point.py", line 153, in route_message
    await self._handle_call(msg)
  File "/home/lenovo/.local/lib/python3.8/site-packages/ocpp/charge_point.py", line 176, in _handle_call
    raise NotSupportedError(
ocpp.exceptions.NotSupportedError: NotSupportedError: Request Action is recognized but not supported by the receiver, {'cause': 'No handler for TriggerMessage registered.'}
INFO:ocpp:CP_1: send [4,"153291687523070501:TM","NotSupported","Request Action is recognized but not supported by the receiver",{"cause":"No handler for TriggerMessage registered."}]
INFO:ocpp:CP_1: receive message [2,"153291687523070501:TM","TriggerMessage",{"requestedMessage":"StatusNotification","connectorId":3}]
ERROR:ocpp:Error while handling request '<Call - unique_id=153291687523070501:TM, action=TriggerMessage, payload={'requestedMessage': 'StatusNotification', 'connectorId': 3}>'
Traceback (most recent call last):
  File "/home/lenovo/.local/lib/python3.8/site-packages/ocpp/charge_point.py", line 174, in _handle_call
    handlers = self.route_map[msg.action]
KeyError: 'TriggerMessage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lenovo/.local/lib/python3.8/site-packages/ocpp/charge_point.py", line 153, in route_message
    await self._handle_call(msg)
  File "/home/lenovo/.local/lib/python3.8/site-packages/ocpp/charge_point.py", line 176, in _handle_call
    raise NotSupportedError(
ocpp.exceptions.NotSupportedError: NotSupportedError: Request Action is recognized but not supported by the receiver, {'cause': 'No handler for TriggerMessage registered.'}
```

If anyone knows how to handle or solve this error, please reply. Thankyou.

**Comment by OrangeTux** [comment]
The CSMS seems to send a TriggerMessage request to your charger. And the charger doesn't seem to implement a handler for that.

**Comment by DvlprSG** [comment]
> The CSMS seems to send a TriggerMessage request to your charger. And the charger doesn't seem to implement a handler for that.

Thanks for helping, after implemeting TriggerMessage handler the problem is solved.

**Comment by cadenxue** [comment]
I also encountered the same problem, may I ask where I should add the processing program, thank you very much
I found that create_route_map returns an empty value of routes in the ocpp.routing.py file
