### ISSUE TITLE
Heartbeat message produces error: No handler for Heartbeat registered

### ISSUE THREAD

**Issue by rzylius** [mobilityhouse/ocpp#460]
Hi,

I started Central System v1.6 code and try to connect ElintaCharge charging station, which supports ocpp v1.6.

BootNotification messages goes through, and error is encountered on Heartbeat, with "cause":"No handler for Heartbeat registered."

What is wrong here?

```
INFO:ocpp:CP_svajos: receive message [2,"3591793962198250472","Heartbeat",{}]
ERROR:ocpp:Error while handling request '<Call - unique_id=3591793962198250472, action=Heartbeat, payload={}>'
Traceback (most recent call last):
  File "C:\GITHUB\ocpp-server\.venv\lib\site-packages\ocpp\charge_point.py", line 174, in _handle_call    handlers = self.route_map[msg.action]
KeyError: 'Heartbeat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\GITHUB\ocpp-server\.venv\lib\site-packages\ocpp\charge_point.py", line 153, in route_message
    await self._handle_call(msg)
  File "C:\GITHUB\ocpp-server\.venv\lib\site-packages\ocpp\charge_point.py", line 176, in _handle_call    raise NotSupportedError(
ocpp.exceptions.NotSupportedError: NotSupportedError: Request Action is recognized but not supported by the receiver, {'cause': 'No handler for Heartbeat registered.'}
INFO:ocpp:CP_svajos: send [4,"3591793962198250472","NotSupported","Request Action is recognized but not supported by the receiver",{"cause":"No handler for Heartbeat registered."}]
DEBUG:websockets.server:> TEXT '[4,"3591793962198250472","NotSupported","Reques...eartbeat registered."}]' [154 bytes]
DEBUG:websockets.server:< TEXT '[2,"3591793962198250473","StatusNotification",{...2023-07-23T19:02:37Z"}]' [142 bytes]
INFO:ocpp:CP_svajos: receive message [2,"3591793962198250473","StatusNotification",{"connectorId":0,"errorCode":"NoError","status":"Available","timestamp":"2023-07-23T19:02:37Z"}]
ERROR:ocpp:Error while handling request '<Call - unique_id=3591793962198250473, action=StatusNotification, payload={'connectorId': 0, 'errorCode': 'NoError', 'status': 'Available', 'timestamp': '2023-07-23T19:02:37Z'}>'
Traceback (most recent call last):
  File "C:\GITHUB\ocpp-server\.venv\lib\site-packages\ocpp\charge_point.py", line 174, in _handle_call    handlers = self.route_map[msg.action]
KeyError: 'StatusNotification'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\GITHUB\ocpp-server\.venv\lib\site-packages\ocpp\charge_point.py", line 153, in route_message
    await self._handle_call(msg)
  File "C:\GITHUB\ocpp-server\.venv\lib\site-packages\ocpp\charge_point.py", line 176, in _handle_call    raise NotSupportedError(
ocpp.exceptions.NotSupportedError: NotSupportedError: Request Action is recognized but not supported by the receiver, {'cause': 'No handler for StatusNotification registered.'}
INFO:ocpp:CP_svajos: send [4,"3591793962198250473","NotSupported","Request Action is recognized but not supported by the receiver",{"cause":"No handler for StatusNotification registered."}]
DEBUG:websockets.server:> TEXT '[4,"3591793962198250473","NotSupported","Reques...fication registered."}]' [163 bytes]
INFO:websockets.server:connection closed
DEBUG:websockets.server:x half-closing TCP connection
DEBUG:websockets.server:= connection is CLOSED
```
`

**Comment by OrangeTux** [comment]
Your code is missing a handler to process inbound Heartbeat requests. See https://github.com/mobilityhouse/ocpp/issues/446 and https://github.com/mobilityhouse/ocpp/issues/405.
