### ISSUE TITLE
DataTransfer Handling

### ISSUE THREAD

**Issue by DvlprSG** [mobilityhouse/ocpp#462]
I am trying to implement the DataTransfer OCPP Usecase, in which I am starting DataTransfer from Central System and trying to receive at charge point. But I am getting some errors.

```
ERROR:ocpp:Error while handling request '<Call - unique_id=153291690525715013:DT, action=DataTransfer, payload={'vendorId': 'btc', 'messageId': 'stationMode', 'data': {'StationMode': 'paymentMode'}}>'
Traceback (most recent call last):
  File "/home/lenovo/.local/lib/python3.8/site-packages/ocpp/messages.py", line 227, in validate_payload
    validator.validate(message.payload)
  File "/home/lenovo/.local/lib/python3.8/site-packages/jsonschema/validators.py", line 314, in validate
    raise error
jsonschema.exceptions.ValidationError: {'StationMode': 'paymentMode'} is not of type 'string'

Failed validating 'type' in schema['properties']['data']:
    {'type': 'string'}

On instance['data']:
    {'StationMode': 'paymentMode'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lenovo/.local/lib/python3.8/site-packages/ocpp/charge_point.py", line 153, in route_message
    await self._handle_call(msg)
  File "/home/lenovo/.local/lib/python3.8/site-packages/ocpp/charge_point.py", line 181, in _handle_call
    validate_payload(msg, self._ocpp_version)
  File "/home/lenovo/.local/lib/python3.8/site-packages/ocpp/messages.py", line 230, in validate_payload
    raise TypeConstraintViolationError(
ocpp.exceptions.TypeConstraintViolationError: TypeConstraintViolationError: Payload for Action is syntactically correct but at least one of the fields violates data type constraints (e.g. “somestring”: 12), {'cause': "{'StationMode': 'paymentMode'} is not of type 'string'", 'ocpp_message': <Call - unique_id=153291690525715013:DT, action=DataTransfer, payload={'vendorId': 'btc', 'messageId': 'stationMode', 'data': {'StationMode': 'paymentMode'}}>}
INFO:ocpp:CP_1: send [4,"153291690525715013:DT","TypeConstraintViolation","Payload for Action is syntactically correct but at least one of the fields violates data type constraints (e.g. \u201csomestring\u201d: 12)",{"cause":"{'StationMode': 'paymentMode'} is not of type 'string'","ocpp_message":"[2,\"153291690525715013:DT\",\"DataTransfer\",{\"vendorId\":\"btc\",\"messageId\":\"stationMode\",\"data\":{\"StationMode\":\"paymentMode\"}}]"}]
```
Code which i written is :
```
@on(action.DataTransfer)
    async def transfer_data(self, vendor_id: str, message_id: list, data: str):
        print(vendor_id, message_id, data)
        return call_result.DataTransferPayload(enums.DataTransferStatus.accepted)
```

RAW Data which i am sending:
```
[
  2,
  "153291690454623056:DT",
  "DataTransfer",
  {
    "vendorId": "greenlots",
    "messageId": "stationMode",
    "data": {
      "StationMode": "paymentMode"
    }
  }
]
```
If any one knows why this error is coming and how to solve this, please share the solution. It will be helpful.

THANKYOU

**Comment by proelke** [comment]
You are sending "data" as a dict not a string. Format it as a string/json and it should work.
