### ISSUE TITLE
OCPP is not a package

### ISSUE THREAD

**Issue by StefanoGiu** [mobilityhouse/ocpp#658]
>>> from ocpp.v201.enums import RegistrationStatusType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ocpp.py", line 3, in <module>
    from ocpp.v201.enums import RegistrationStatusType
ModuleNotFoundError: No module named 'ocpp.v201'; 'ocpp' is not a package

**Comment by OrangeTux** [comment]
It seems that your script is called `ocpp.py`. Try renaming the file.

**Comment by jainmohit2001** [comment]
Closing this issue due to inactivity. Please open it again if the issue persists.
