### ISSUE TITLE
Why it seems that central system requires a handler for remote start transaction? 

### ISSUE THREAD

**Issue by luizhenriquemaia** [mobilityhouse/ocpp#674]
Hello, sorry if this is a dumb question, but I have this implementation of the central system using this library to communicate with real charge points and it seems that to send a call the ChargePoint class needs to implement a handler, but why? Shouldn't the central system expect the call result to come from the charge point and not from the implementation in the central system?

My code is something like this
charge_point.py
```
class ChargePoint(cp):

    # @on("RemoteStartTransaction") <---- this is required? Why? 
    # async def on_remote_start_transaction(self, **kwargs):
    #     return call_result.RemoteStartTransactionPayload(
    #         status=enums.RemoteStartStopStatus.accepted
    #     )

    async def send_remote_start(self, id_tag: int, connector_id: int | None = None):
        request = call.RemoteStartTransaction(id_tag=id_tag, connector_id=connector_id)
        response = await self.call(request)
        if response.status == "Accepted":
            raise Exception("Concluido")
        else:
            raise Exception("Erro")
```
actions.py
```
class ChargePointActions:
    @classmethod
    async def send_remote_start(
        cls, tag_id: int | str, connector_local_id: int, cp_websocket_name: str
    ) -> ActionResponses:
        """Send a remote start transaction call to charge point"""
        async with websockets.connect(
            cls.__get_url(cp_websocket_name), subprotocols=["ocpp1.6"]
        ) as ws: 
            cp = ChargePoint(cp_websocket_name, ws, response_timeout=60)
            try:
                await asyncio.gather(
                    cp.start(), cp.send_remote_start(str(tag_id), connector_local_id)
                )
            except Exception as e:
                logger.error(str(e))
```
The connection works and the remote start transaction payload is sent, but before the real (physically installed) charge point responds to the call, the charge point implementation that I mentioned above responds with the error: `[4,"0d570d9f-0821-4dda-a505-83339ce352d8","NotImplemented","Request Action is recognized but not supported by the receiver",{"cause":"No handler for RemoteStartTransaction registered."}]` Should this happen? Shouldn't the central system wait for the response from the real charge point?

**Comment by a-alak** [comment]
Not sure that is the actual problem, but I am wondering why you are connecting to a websocket? 
If this is the code for the CSMS, shouldn't you be serving a websocket endpoint.

And what URL are you connecting to in the ChargePointActions.send_remote_start, because chargepoints do not usually have serve endpoints? Or am I completely misunderstanding the actions.py file to be CSMS code?

Could you also provide the logs of the OCPP messages? You should see all incoming and outgoing messages in the INFO log.

**Comment by luizhenriquemaia** [comment]
Oh i'm sorry, my english is not very good, I don't think I was able to explain the context properly.
So, this server is using fastapi framework and has a endpoint that charge points connects to:
```
@app.websocket(r"/ocpp/{cp_ws_name}")
async def websocket_charge_point(websocket: WebSocket):
    consumer = ChargePointConsumer(websocket, redis_client)
    await consumer.connect()
```
consumers.py
```
class ChargePointConsumer:

    def __init__(self, websocket: WebSocket, redis_client: StrictRedis) -> None:
        self.websocket = websocket
        self.cp_ws_name = websocket.path_params["cp_ws_name"]
        self.redis_client = redis_client
        self.pubsub = self.redis_client.pubsub()
        return

    async def connect(self):
        try:
            await self.websocket.accept(subprotocol="ocpp1.6")
        except (
            websockets.exceptions.InvalidStatusCode,
            websockets.legacy.exceptions.InvalidStatusCode,
        ) as e:
            print(
                f"Connection {self.cp_ws_name} failed with status code: {e.status_code}"
            )
            await self.websocket.close()
        self.pubsub.subscribe(self.channel_name)

        async def consume():
            while True:
                message = self.pubsub.get_message()
                if message and message["type"] == "message":
                    await self.websocket.send_text(f"{message['data']}")
                await asyncio.sleep(0.1)

        self.redis_task = asyncio.create_task(consume())
        await self.receive()
```
This is the logs without the `@on("RemoteStartTransaction")` and the charge point disconected from websocket, i was expected a timeout but instead i got this NotImplementedError error 
```
2024-10-28 17:50:40 ocpp-v2         | INFO:     ('172.25.0.3', 44332) - "WebSocket /ocpp/Ues-Lagiv79UKJuW-Pod29" [accepted]
2024-10-28 17:50:40 ocpp-v2         | INFO:     connection open
2024-10-28 17:50:40 ocpp-v2         | 2024-10-28 20:50:40,674 [INFO] ocpp: Ues-Lagiv79UKJuW-Pod29 send [2,"c0754741-ed4c-45e1-bf3b-3664a2afe5da","RemoteStartTransaction",{"idTag":"2","connectorId":1}]
2024-10-28 17:50:41 ocpp-v2         | 2024-10-28 20:50:41,976 [INFO] app.gateways.charge_points.consumer: Servidor | Virtual EVSE(9) | [2,"c0754741-ed4c-45e1-bf3b-3664a2afe5da","RemoteStartTransaction",{"idTag":"2","connectorId":1}]
2024-10-28 17:50:42 ocpp-v2         | 2024-10-28 20:50:42,191 [INFO] ocpp: Ues-Lagiv79UKJuW-Pod29: receive message [2,"c0754741-ed4c-45e1-bf3b-3664a2afe5da","RemoteStartTransaction",{"idTag":"2","connectorId":1}]
2024-10-28 17:50:42 ocpp-v2         | 2024-10-28 20:50:42,456 [ERROR] ocpp: Error while handling request '<Call - unique_id=c0754741-ed4c-45e1-bf3b-3664a2afe5da, action=RemoteStartTransaction, payload={'idTag': '2', 'connectorId': 1}>'
2024-10-28 17:50:42 ocpp-v2         | Traceback (most recent call last):
2024-10-28 17:50:42 ocpp-v2         |   File "/opt/venv/lib/python3.11/site-packages/ocpp/charge_point.py", line 283, in _handle_call
2024-10-28 17:50:42 ocpp-v2         |     handlers = self.route_map[msg.action]
2024-10-28 17:50:42 ocpp-v2         |                ~~~~~~~~~~~~~~^^^^^^^^^^^^
2024-10-28 17:50:42 ocpp-v2         | KeyError: 'RemoteStartTransaction'
2024-10-28 17:50:42 ocpp-v2         | 
2024-10-28 17:50:42 ocpp-v2         | During handling of the above exception, another exception occurred:
2024-10-28 17:50:42 ocpp-v2         | 
2024-10-28 17:50:42 ocpp-v2         | Traceback (most recent call last):
2024-10-28 17:50:42 ocpp-v2         |   File "/opt/venv/lib/python3.11/site-packages/ocpp/charge_point.py", line 261, in route_message
2024-10-28 17:50:42 ocpp-v2         |     await self._handle_call(msg)
2024-10-28 17:50:42 ocpp-v2         |   File "/opt/venv/lib/python3.11/site-packages/ocpp/charge_point.py", line 285, in _handle_call
2024-10-28 17:50:42 ocpp-v2         |     _raise_key_error(msg.action, self._ocpp_version)
2024-10-28 17:50:42 ocpp-v2         |   File "/opt/venv/lib/python3.11/site-packages/ocpp/charge_point.py", line 170, in _raise_key_error
2024-10-28 17:50:42 ocpp-v2         |     raise NotImplementedError(
2024-10-28 17:50:42 ocpp-v2         | ocpp.exceptions.NotImplementedError: NotImplementedError: Request Action is recognized but not supported by the receiver,  {'cause': 'No handler for RemoteStartTransaction registered.'}
2024-10-28 17:50:42 ocpp-v2         | 2024-10-28 20:50:42,457 [INFO] ocpp: Ues-Lagiv79UKJuW-Pod29: send [4,"c0754741-ed4c-45e1-bf3b-3664a2afe5da","NotImplemented","Request Action is recognized but not supported by the receiver",{"cause":"No handler for RemoteStartTransaction registered."}]
```
You need some other information?

**Comment by a-alak** [comment]
Okay i have a suspicion! 
In the logs you see that line 3 you send the remote start message to the charge point.
Then in line 5 you receive the exact same remote start message from the charge point. 
We have two issues:
1) the charge point is supposed to respond with a call result (id 3 not id 2), but is responding with a call instead
2) the charge point is never supposed to send a remote start request

I suspect that what you are accidentally doing is making the CSMS connect to it self as a chargepoint, and send it self the remote transaction request. 
In actions.py you do the following:
1. connect to a websocket url, which I suppose is the url to your CSMS with the id of the charge point. This means that when you do a call, the charge point class will send it to the websocket, that the same charge point class is listening to. 
The cp object is calling e.g. "{your_url}/ocpp/Ues-Lagiv79UKJuW-Pod29" and is listening to the same url. 
2. You do cp.start(), which means that every message sent to "{your_url}/ocpp/Ues-Lagiv79UKJuW-Pod29" is handled by that cp instance.
3. You run the cp.send_remote_start which sends a remote start transaction to "{your_url}/ocpp/Ues-Lagiv79UKJuW-Pod29" and not to a actual Chargepoint, this then is received by the same instance of the cp object, that is listening on that websocket connection.

Instead, what you want to do, is have your fastapi handler (websocket_charge_point) instantiate a ChargePoint object when a physical charge point connects to your server. Then you need to keep track of the created ChargePoint objects, so when you wish to start a remote transaction, you call cp.send_remote_start on the right object. 

I have limited experience with fastapi and have not at all worked with websockets in fastapi, but I imagine that you would in your ChargePointConsumer after accepting a connection, instantiate a ChargePoint object with that connection. 
Then I imagine (depending on the planned setup you have), that the pubsub channel would receive some form of user input for remote transaction, that needs to be translated to calling cp.send_remote_start.

**Comment by luizhenriquemaia** [comment]
Thank you very much for your time and for responding so quickly, that was indeed the problem, I managed to fix it!

**Comment by proelke** [comment]
On this note, I think it's really overdue to build out the documentation for this library which would solve a lot of questions. Providing more practical examples with different frameworks and context. @jainmohit2001  @mdwcrft I think this should be the next major effort on this library.

**Comment by a-alak** [comment]
Would love to help updating the documentation!

**Comment by jainmohit2001** [comment]
> On this note, I think it's really overdue to build out the documentation for this library which would solve a lot of questions. Providing more practical examples with different frameworks and context. @jainmohit2001 @mdwcrft I think this should be the next major effort on this library.

Agreed.

**Comment by jainmohit2001** [comment]
> Would love to help updating the documentation!

You are welcome to raise relevant PR's.

**Comment by mdwcrft** [comment]
@luizhenriquemaia please close this issue if you're happy with the solution
