### ISSUE TITLE
Sending a SetChargeProfile call fails with TypeError

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#68]
Version `0.6.0` forces validation of `Call`s before the are send to the other end. The validation of `call.SetChargingProfilePayload` fails with a TypeError. The charging profile contains a value of type `decimal.Decimal` and this value cannot be serialized to JSON. The problem can be demonstrated like this:

``` python
>>> import decimal
>>> import json
>>> >>> json.dumps(decimal.Decimal(3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/developer/.pyenv/versions/3.7.0/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/developer/.pyenv/versions/3.7.0/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/developer/.pyenv/versions/3.7.0/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/developer/.pyenv/versions/3.7.0/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable
```

**Comment by tropxy** [comment]
After a short research it seems we have 2 options:

1) is to follow the suggestion in this python blog message that @OrangeTux found:
[https://bugs.python.org/issue16535#msg176158](https://bugs.python.org/issue16535#msg176158)

2) Add simplejson as dependency. simplejson supports natively Decimal serialization:
[https://simplejson.readthedocs.io/en/latest/](https://simplejson.readthedocs.io/en/latest/)
